config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :reference_id, presence: true
  validates :name, uniqueness: { scope: :reference_id }
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  monetize :amount_cents, allow_nil: false

  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show ]

  # GET /invoices
  def index
    @invoices = Invoice.all.order(created_at: :desc)
  end

  # GET /invoices/1
  def show
  end

  # GET /invoices/new
  def new
    @invoice = InvoiceForm.new
  end

  # POST /invoices
  def create
    @invoice = InvoiceForm.new(invoice_params)
    respond_to do |format|
      if @invoice.valid?
        @invoice = @invoice.save
        format.html { redirect_to invoice_path(@invoice), notice: "Invoice was successfully raised." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice_form).permit(:description, :amount, :amount_currency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
  def status(invoice)
    if invoice.approved_at
      'approved'
    elsif invoice.rejected_at
      'rejected'
    else
      'pending for approval'
    end
  end
end

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">

  <p>
    <strong>Invoice id:</strong>
    <%= invoice.id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= invoice.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= invoice.amount %>
  </p>

  <p>
    <strong>Amount currency:</strong>
    <%= invoice.amount_currency %>
  </p>


  <p>
    <strong>status:</strong>
    <%= status(invoice) %>
  </p>

</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoices</h1>

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
    <p>
      <%= link_to "Show this invoice", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= simple_form_for @invoice, url: invoices_path do |f| %>
  <%= f.input :description, required: true %>
  <%= f.input :amount, required: true, as: :integer %>
  <%= f.input :amount_currency, required: true %>
  <%= f.button :submit %>

<% end %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContractorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>